name: build and test

on:
  push:
  pull_request:
    branches: [ master ]
    paths:
      - '**.cs'
      - '**.csproj'

env:
  DOTNET_NOLOGO: true

jobs:
  build-and-test:

    name: Build + Test
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os: [ ubuntu, windows, macOS ]

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.x

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          architecture: x64

      - name: Install Gym + dependencies  # for tests
        run: |
          pip install gym pyglet numpy
          pip install pythonnet==3.0.0a2 --pre

      - name: Set Python DLL path (non Windows)
        if: ${{ matrix.os != 'windows' }}
        run: |
          python -m pythonnet.find_libpython --export >> $GITHUB_ENV

      - name: Set Python DLL path (Windows)
        if: ${{ matrix.os == 'windows' }}
        run: |
          python -m pythonnet.find_libpython --export | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --no-restore --verbosity normal
